const TRANSCRIBE_MODEL='gemini-3.5-transcribe';
const API='https://generativelanguage.googleapis.com';
function env(n){const v=process.env[n];if(!v)throw new Error(`Missing environment variable: ${n}`);return v}
function out(res,s,b){return res.status(s).json(b)}
function sec(v){const m=String(v??'').match(/^([0-9.]+)s$/);return m?Number(m[1]):NaN}
function norm(v){return String(v||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9']+/g,'').trim()}
function scriptWords(s){return String(s||'').replace(/\s+/g,' ').trim().split(' ').filter(Boolean)}
function annotations(data){const a=[];for(const step of data?.steps||[])for(const content of step?.content||[])for(const x of content?.annotations||[])if(x?.type==='word_info'){const s=sec(x.start_offset),e=sec(x.end_offset),t=String(x.text||'').trim();if(t&&Number.isFinite(s)&&Number.isFinite(e)&&e>s)a.push({text:t,start:s,end:e})}return a}
function similarity(a,b){const x=norm(a),y=norm(b);if(!x||!y)return 0;if(x===y)return 1;const m=x.length,n=y.length,dp=Array.from({length:m+1},(_,i)=>{const r=new Array(n+1);r[0]=i;return r});for(let j=1;j<=n;j++)dp[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(x[i-1]===y[j-1]?0:1));return 1-dp[m][n]/Math.max(m,n)}
function align(script,raw){
 const target=scriptWords(script), r=raw.map(x=>({...x,k:norm(x.text)})), n=target.length,m=r.length, NEG=-1e9;
 const dp=Array.from({length:n+1},()=>new Array(m+1).fill(NEG)), back=Array.from({length:n+1},()=>new Array(m+1).fill(null)); dp[0][0]=0;
 for(let i=0;i<=n;i++)for(let j=0;j<=m;j++){
  if(i<n&&j<m){const sim=similarity(target[i],r[j].text);if(sim>=0.62&&dp[i][j]+sim*3.2>dp[i+1][j+1]){dp[i+1][j+1]=dp[i][j]+sim*3.2;back[i+1][j+1]=['match',i,j]}}
  if(j<m&&dp[i][j]-0.55>dp[i][j+1]){dp[i][j+1]=dp[i][j]-0.55;back[i][j+1]=['skip_raw',i,j]}
  if(i<n&&dp[i][j]-1.35>dp[i+1][j]){dp[i+1][j]=dp[i][j]-1.35;back[i+1][j]=['skip_target',i,j]}
 }
 const matched=new Array(n).fill(null);let i=n,j=m;while(i>0||j>0){const b=back[i][j];if(!b)break;const [kind,pi,pj]=b;if(kind==='match')matched[pi]=r[pj];i=pi;j=pj}
 const missing=target.map((w,k)=>matched[k]?null:`${k+1}:${w}`).filter(Boolean);
 if(missing.length)throw new Error(`Gemini did not provide real timestamps for script words: ${missing.join(', ')}`);
 let last=-1;return matched.map((x,k)=>{if(x.start<=last||x.end<=x.start)throw new Error(`Non-monotonic Gemini timing at word ${k+1}: ${target[k]}`);last=x.start;return{text:target[k],start:x.start,end:x.end}})
}
async function uploadFile(bytes,key){const start=await fetch(`${API}/upload/v1beta/files`,{method:'POST',headers:{'x-goog-api-key':key,'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(bytes.length),'X-Goog-Upload-Header-Content-Type':'audio/wav','Content-Type':'application/json'},body:JSON.stringify({file:{display_name:`unmindy-strict-${Date.now()}.wav`}})});const t=await start.text();if(!start.ok){const e=new Error(`Gemini Files start ${start.status}: ${t}`);e.status=start.status;throw e}const url=start.headers.get('x-goog-upload-url');if(!url)throw new Error('Gemini Files API returned no upload URL');const finish=await fetch(url,{method:'POST',headers:{'Content-Length':String(bytes.length),'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize'},body:bytes});const d=await finish.json().catch(()=>({}));if(!finish.ok){const e=new Error(`Gemini Files upload ${finish.status}: ${JSON.stringify(d)}`);e.status=finish.status;throw e}if(!d?.file?.uri)throw new Error(`Gemini Files upload returned no URI: ${JSON.stringify(d)}`);return{name:d.file.name,uri:d.file.uri}}
async function transcribe(bytes,script,key){let f;try{f=await uploadFile(bytes,key);const r=await fetch(`${API}/v1beta/interactions`,{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({model:TRANSCRIBE_MODEL,input:[{type:'audio',uri:f.uri,mime_type:'audio/wav'}],generation_config:{transcription_config:{mode:{type:'verbatim',timestamp_granularities:['word']},language_codes:['en-IN']}}})});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(`Gemini transcription ${r.status}: ${JSON.stringify(d)}`);e.status=r.status;throw e}return align(script,annotations(d))}finally{if(f?.name)fetch(`${API}/v1beta/${f.name}`,{method:'DELETE',headers:{'x-goog-api-key':key}}).catch(()=>{})}}
export default async function handler(req,res){try{if(req.method!=='POST')return out(res,405,{error:'POST only'});if(req.headers.authorization!==`Bearer ${env('CRON_SECRET')}`)return out(res,401,{ok:false,error:'Unauthorized'});const {audioUrl,script}=req.body||{};if(!audioUrl||!script)return out(res,400,{ok:false,error:'audioUrl and script are required'});const ar=await fetch(audioUrl);if(!ar.ok)throw new Error(`Audio download failed: ${ar.status}`);const bytes=Buffer.from(await ar.arrayBuffer());if(bytes.length>25*1024*1024)throw new Error(`Audio too large: ${bytes.length}`);const keys=['GEMINI_API_KEY_1','GEMINI_API_KEY_2','GEMINI_API_KEY_3','GEMINI_API_KEY'].map(n=>process.env[n]).filter(Boolean);if(!keys.length)throw new Error('No Gemini API key configured');const failures=[];for(let i=0;i<keys.length;i++){try{return out(res,200,{ok:true,model:TRANSCRIBE_MODEL,words:await transcribe(bytes,script,keys[i])})}catch(e){const status=e?.status;failures.push(`key${i+1}: ${e instanceof Error?e.message:String(e)}`);if(status===401||status===403||status===429)continue;throw e}}throw new Error(`All Gemini API keys failed. ${failures.join(' | ')}`)}catch(e){console.error(e);return out(res,500,{ok:false,error:e instanceof Error?e.message:String(e)})}}
