// v15: use the Vercel CRON_SECRET name used by the edit endpoints.
const TRANSCRIBE_MODEL='gemini-3.5-transcribe';
const API='https://generativelanguage.googleapis.com';
function env(n){const v=process.env[n];if(!v)throw new Error(`Missing environment variable: ${n}`);return v}
function out(res,s,b){return res.status(s).json(b)}
function sec(v){const m=String(v??'').match(/^([0-9.]+)s$/);return m?Number(m[1]):NaN}
function norm(v){return String(v||'').toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9']+/g,'').trim()}
function annotations(data){const a=[];for(const step of data?.steps||[])for(const content of step?.content||[])for(const x of content?.annotations||[])if(x?.type==='word_info'){const s=sec(x.start_offset),e=sec(x.end_offset),t=String(x.text||'').trim();if(t&&Number.isFinite(s)&&Number.isFinite(e)&&e>=s)a.push({text:t,start:s,end:e})}return a}
function align(script,raw){const target=String(script).replace(/\s+/g,' ').trim().split(' ').filter(Boolean),r=raw.map(x=>({...x,k:norm(x.text)})),ans=[];let c=0;for(const word of target){const k=norm(word);let hit=-1;for(let j=c;j<Math.min(r.length,c+10);j++){if(r[j].k===k){hit=j;break}}if(hit>=0){ans.push({text:word,start:r[hit].start,end:r[hit].end});c=hit+1}else ans.push({text:word,start:null,end:null})}let matched=ans.filter(x=>Number.isFinite(x.start)).length;if(matched<Math.floor(target.length*.85))throw new Error(`Transcription alignment too weak: ${matched}/${target.length}`);for(let i=0;i<ans.length;i++)if(!Number.isFinite(ans[i].start)){let p=i-1;while(p>=0&&!Number.isFinite(ans[p].start))p--;let n=i+1;while(n<ans.length&&!Number.isFinite(ans[n].start))n++;if(p>=0&&n<ans.length){const gap=(ans[n].start-ans[p].end)/(n-p);ans[i].start=ans[p].end+gap*(i-p);ans[i].end=ans[i].start+Math.min(.16,gap*.7)}else if(p>=0){ans[i].start=ans[p].end;ans[i].end=ans[i].start+.12}else{ans[i].start=Math.max(0,ans[n].start-.12);ans[i].end=ans[n].start}}return ans}
async function uploadFile(bytes,mime){const start=await fetch(`${API}/upload/v1beta/files`,{method:'POST',headers:{'x-goog-api-key':env('GEMINI_API_KEY'),'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(bytes.length),'X-Goog-Upload-Header-Content-Type':mime,'Content-Type':'application/json'},body:JSON.stringify({file:{display_name:`unmindy-tts-${Date.now()}.wav`}})});const startText=await start.text();if(!start.ok)throw new Error(`Gemini Files start ${start.status}: ${startText}`);const uploadUrl=start.headers.get('x-goog-upload-url');if(!uploadUrl)throw new Error('Gemini Files API returned no upload URL');const finish=await fetch(uploadUrl,{method:'POST',headers:{'Content-Length':String(bytes.length),'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize'},body:bytes});const d=await finish.json().catch(()=>({}));if(!finish.ok)throw new Error(`Gemini Files upload ${finish.status}: ${JSON.stringify(d)}`);const uri=d?.file?.uri;if(!uri)throw new Error(`Gemini Files upload returned no URI: ${JSON.stringify(d)}`);return {uri,name:d?.file?.name}}
async function deleteFile(name){if(!name)return;await fetch(`${API}/v1beta/${name}`,{method:'DELETE',headers:{'x-goog-api-key':env('GEMINI_API_KEY')}}).catch(()=>{})}
export default async function handler(req,res){let uploaded;try{if(req.method!=='POST')return out(res,405,{error:'POST only'});if(req.headers.authorization!==`Bearer ${env('CRON_SECRET')}`)return out(res,401,{ok:false,error:'Unauthorized'});const {audioUrl,script}=req.body||{};if(!audioUrl||!script)return out(res,400,{ok:false,error:'audioUrl and script are required'});const ar=await fetch(audioUrl);if(!ar.ok)throw new Error(`Audio download failed: ${ar.status}`);const bytes=Buffer.from(await ar.arrayBuffer());if(bytes.length>25*1024*1024)throw new Error(`Audio too large: ${bytes.length}`);uploaded=await uploadFile(bytes,'audio/wav');const gr=await fetch(`${API}/v1beta/interactions`,{method:'POST',headers:{'x-goog-api-key':env('GEMINI_API_KEY'),'Content-Type':'application/json'},body:JSON.stringify({model:TRANSCRIBE_MODEL,input:[{type:'audio',uri:uploaded.uri,mime_type:'audio/wav'}],generation_config:{transcription_config:{mode:{type:'verbatim',timestamp_granularities:['word']},language_codes:['en-IN']}}})});const data=await gr.json().catch(()=>({}));if(!gr.ok)throw new Error(`Gemini transcription ${gr.status}: ${JSON.stringify(data)}`);const raw=annotations(data);if(!raw.length)throw new Error(`Gemini returned no word timestamps: ${JSON.stringify(data).slice(0,4000)}`);return out(res,200,{ok:true,model:TRANSCRIBE_MODEL,words:align(script,raw)})}catch(e){console.error(e);return out(res,500,{ok:false,error:e instanceof Error?e.message:String(e)})}finally{if(uploaded?.name)await deleteFile(uploaded.name)}}
